language: python
sudo: required
python:
    - "2.7"
before_install:
    - sudo apt-get install fabric liblua5.2 liblua5.2-dev
install:
    - pip install flake8
    - pip install -r requirements.txt
script:
    - ./tools/infrastructure/test/check-style.sh
    - fab test_all
